
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checking maven/java version
      run: |
        java -version
        mvn -version
        ls -lrth
        
    - name: Validating POM.xml file
      run: mvn validate

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Clean
      run: mvn clean

    - name: Package
      run: mvn package

    - name:  Create package
      run: |
        mvn package
        ls -lrth target/
        
    - name:  Execute Jar 
      run: java -cp target/mavenleap-1.0-SNAPSHOT.jar com.sudharsanan.leap.App
  
        
    - name: Uplaod artifact in workflow
      uses: actions/upload-artifact@v3
      with:
          name: maven-demo-artifact
          path: target/mavenleap-1.0-SNAPSHOT.jar
      

  
